# Generated by Django 4.2.6 on 2024-01-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_sous_categorie_perruque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sous_categorie_PERRUQUE',
        ),
    ]
