# Generated by Django 4.2.6 on 2024-01-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_sous_categorie_perruque'),
    ]

    operations = [
        migrations.CreateModel(
            name='SousCategoriePerruque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, null=True)),
            ],
        ),
    ]
