# Generated by Django 4.2.6 on 2024-01-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_souscategorieperruque'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscategorieperruque',
            name='slug_name',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', unique=True),
        ),
    ]
