# Generated by Django 4.2.6 on 2024-01-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_souscategorieperruque_slug_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(default='perruques', max_length=16, null=True),
        ),
    ]
