# Generated by Django 4.2.6 on 2024-01-06 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_categorie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sous_categorie_perruque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.souscategorieperruque'),
        ),
    ]
