# Generated by Django 4.2.6 on 2024-01-06 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_sous_categorie_perruque'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SousCategoriePerruque',
            new_name='SousCategoriePerruques',
        ),
    ]
