# Generated by Django 4.2.6 on 2024-01-06 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_souscategorieperruque_souscategorieperruques'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerruqueSousCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, null=True)),
                ('slug_name', models.SlugField(default=' ', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='sous_categorie_perruque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.perruquesouscategorie'),
        ),
        migrations.DeleteModel(
            name='SousCategoriePerruques',
        ),
    ]
