# Generated by Django 4.2.6 on 2024-01-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_perruquesouscategorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perruquesouscategorie',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
