# Generated by Django 4.2.6 on 2023-12-03 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField(default=450.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=880.0)),
                ('tax', models.FloatField(default=0.2)),
                ('delivery_price', models.FloatField(default=0.0)),
                ('quantity_total', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.article')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('Adresse', models.CharField(max_length=150)),
                ('adresse_complementaire', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(max_length=40)),
                ('Ville', models.CharField(max_length=60)),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassicOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PAIEMENT NON validé', 'Non Paye'), ('PAIEMENT validé', 'Paiement Valide'), ('EXPEDITION EN COURS', 'Expedie'), ('COMMANDE LIVREE', 'Livre'), ('COMMANDE Annulée', 'Annulee')], max_length=25)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.cart')),
                ('delivery_adress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.delivery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnonymousOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PAIEMENT NON validé', 'Non Paye'), ('PAIEMENT validé', 'Paiement Valide'), ('EXPEDITION EN COURS', 'Expedie'), ('COMMANDE LIVREE', 'Livre'), ('COMMANDE Annulée', 'Annulee')], max_length=25)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.cart')),
                ('delivery_adress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.delivery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
