# Generated by Django 4.2.6 on 2023-12-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='phone_number',
            field=models.IntegerField(default='0123456789'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cart',
            name='articles',
        ),
        migrations.AddField(
            model_name='cart',
            name='articles',
            field=models.ManyToManyField(to='orders.article'),
        ),
    ]
