# Generated by Django 4.2.6 on 2023-12-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delivery_phone_number_remove_cart_articles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymousorder',
            name='product',
        ),
        migrations.AddField(
            model_name='article',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
