# Generated by Django 4.2.6 on 2023-12-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_anonymousorder_product_article_ordered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classicorder',
            name='delivery_adress',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.delivery'),
        ),
        migrations.AlterField(
            model_name='classicorder',
            name='status',
            field=models.CharField(choices=[('PAIEMENT NON validé', 'Non Paye'), ('PAIEMENT validé', 'Paiement Valide'), ('EXPEDITION EN COURS', 'Expedie'), ('COMMANDE LIVREE', 'Livre'), ('COMMANDE Annulée', 'Annulee')], default='PAIEMENT NON validé', max_length=25),
        ),
    ]
