# Generated by Django 4.2.6 on 2023-12-21 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_classicorder_delivery_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousorder',
            name='delivery_adress',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.delivery'),
        ),
    ]
