# Generated by Django 4.2.6 on 2023-12-21 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_anonymousorder_delivery_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymousorder',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='anonymousorder',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cart'),
        ),
        migrations.AlterField(
            model_name='anonymousorder',
            name='delivery_adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.delivery'),
        ),
        migrations.AlterField(
            model_name='classicorder',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cart'),
        ),
        migrations.AlterField(
            model_name='classicorder',
            name='delivery_adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.delivery'),
        ),
    ]
